enum TextName {
  MAIN = 'MAIN',
  BUTTON = 'BUTTON',
  TITLE_H1 = 'TITLE_H1',
  TITLE_H2 = 'TITLE_H2',
  TITLE_H3 = 'TITLE_H3',
  TITLE_H4 = 'TITLE_H4',
  INPUT = 'INPUT',
  INPUT_LABEL = 'INPUT_LABEL',
  MESSAGE_TEXT = 'MESSAGE_TEXT',
  MESSAGE_TITLE = 'MESSAGE_TITLE',
}

export default TextName;
